### ISSUE TITLE
display data from our plugin [blocker- we didn't complete it on plugin side]

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/react-native-shoppin-list#12]

**Comment by atherdon** [comment]
in our `grocery-fetch` plugin we add json arrays, that will be good help to you. it's an actual data from our database, so it'll help you with testing and will not require connection to our database and API at first stages. we didn't finish your part completely, but it'll be done soon. i'll let you know

@vineeshvk

**Comment by vineeshvk** [comment]
Okay

**Comment by atherdon** [comment]
btw, keep in mind that you'll need to update this plugin to lastest changes when we'll finish it

**Comment by vineeshvk** [comment]
Can you show me the structure of the json.

**Comment by vineeshvk** [comment]
Yeah sure

**Comment by vineeshvk** [comment]
Okay

**Comment by atherdon** [comment]
https://github.com/GroceriStar/groceristar-fetch/tree/master/data/Departments
https://github.com/GroceriStar/groceristar-fetch/tree/master/data/Grocery
https://github.com/GroceriStar/groceristar-fetch/tree/master/data/Ingredients

https://github.com/GroceriStar/groceristar-fetch/tree/master/data/Users

sorry for slow reply. i think i just forgot to hit enter and my PC then rebooted

**Comment by atherdon** [comment]
we'll also create a wrapper for it, so you'll need just to call function that we have and anything will be as you need. so you'll just looping the data inside some components

**Comment by atherdon** [comment]
@vineeshvk we updated our plugin so it have data that you'll need while we didn't connect to our database and created a set of methods to get that data from json files. 
Check the readme and tell me if something is not clear, ok? https://github.com/GroceriStar/groceristar-fetch

**Comment by vineeshvk** [comment]
Yeah it's clear. And can change all that to es6.

**Comment by atherdon** [comment]
you mean is this possible to use `import` of that package in your repository?

**Comment by vineeshvk** [comment]
Yeah

**Comment by atherdon** [comment]
yes, we updated our repository readme, please check how it works and list of methods here: https://github.com/GroceriStar/groceristar-fetch#get-an-array-of-ingredients-groceristar-part

`import gf from '@groceristar/groceristar-fetch'` will works.

**Comment by vineeshvk** [comment]
Yeah I checked. Every thing works except `getAllIngredientsByOneDepartment('Fresh vegetables');`.
Can you test whether it works or not?

**Comment by atherdon** [comment]
can you create an issue in groceristar-fetch module repository and mention
some of our developers from that repo? i'm pretty sure it'll be a fast fix


On 16-Jul-2018 at 01:50 PM, Vineesh VK wrote:


Yeah I checked. Every thing works except
getAllIngredientsByOneDepartment('Fresh
vegetables');.
Can you test whether it works or not?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/GroceriStar/react-native-shoppin-list/issues/12#issuecomment-405254033>,
or mute the thread

**Comment by atherdon** [comment]
@vineeshvk  hold on, i'll help you

**Comment by vineeshvk** [comment]
Okay.

**Comment by atherdon** [comment]
Plugin was fixed, and the latest version was merged to master branch. please checkout and tell if everything working well

**Comment by vineeshvk** [comment]
It's still not working for me. I don't know whether I'm doing something wrong. `gf.getAllIngredientsByOneDepartment('Fresh vegetables'); and getAllDepartments too` is not working but all others are working.

**Comment by atherdon** [comment]
@vadim9999 can you help us?

@vineeshvk did you grab the latest version of plugin that i've merged into this repository?

**Comment by atherdon** [comment]
it's should be 1.1.7 version. if in latest version you still experience the error - then this is on plugin side issue and we'll take a look

**Comment by vadim9999** [comment]
@vineeshvk I tested this two methods and it is working good. Can you past logs?

**Comment by vineeshvk** [comment]
when I use 
![screenshot from 2018-07-19 18 24 06](https://user-images.githubusercontent.com/25723863/42944150-8c081c70-8b82-11e8-8ea0-9b3b733c919a.png)
I get the error
![screenshot_1532005334](https://user-images.githubusercontent.com/25723863/42944183-9e317f4a-8b82-11e8-8998-0d78032388af.png)
And when I use this
![screenshot from 2018-07-19 18 33 57](https://user-images.githubusercontent.com/25723863/42944205-acb2bbce-8b82-11e8-9178-b951144e34f1.png)
I get
![screenshot_1532005418](https://user-images.githubusercontent.com/25723863/42944236-be405996-8b82-11e8-800c-dcf7b2a56790.png)

**Comment by atherdon** [comment]
@vadim9999 i think first issue related to underscore package. i think we didn't include it well. about second  - don't really now.

**Comment by atherdon** [comment]
we're doing to solve first issue soon.
second looks like not a big problem, but we still investigating it

**Comment by atherdon** [comment]
@vineeshvk i merged a PR with updated version of plugin. please check if it works now. Btw, review the readme of it, we did some changes at method names: https://github.com/GroceriStar/groceristar-fetch/blob/master/README.md

**Comment by vineeshvk** [comment]
Sure I'll check it.

On Jul 21, 2018 9:42 PM, "Arthur Tkachenko" <notifications@github.com>
wrote:

@vineeshvk <https://github.com/vineeshvk> i merged a PR with updated
version of plugin. please check if it works now. Btw, review the readme of
it, we did some changes at method names:
https://github.com/GroceriStar/groceristar-fetch/blob/master/README.md

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/GroceriStar/react-native-shoppin-list/issues/12#issuecomment-406806982>,
or mute the thread

**Comment by vineeshvk** [comment]
Now it works perfectly.

**Comment by atherdon** [comment]
thank you for let us know


On 22-Jul-2018 at 09:10 AM, Vineesh VK wrote:


Now it works perfectly.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/GroceriStar/react-native-shoppin-list/issues/12#issuecomment-406851907>,
or mute the thread
